CREATE TYPE "LeadStage" AS ENUM (
    'NEW_LEAD',
    'QUALIFIED',
    'CONSULTATION_BOOKED',
    'PROPOSAL_SENT',
    'CONVERTED',
    'NURTURE',
    'LOST'
);

ALTER TABLE "Inquiry"
ADD COLUMN "leadStage" "LeadStage" NOT NULL DEFAULT 'NEW_LEAD',
ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
